<table class="container table table-striped table-hover">
    <tr>
        <th>Número de temporada</th>
        <th>Título</th>
        <th>Cantidad de Capítulos</th>
        <th>Ver</th>
        <?php
        if(!empty($_SESSION['rol_id'])){
                if($_SESSION['rol_id']==1){
            ?>
                    <th>Editar</th>
                    <th>Eliminar</th>
            <?php
            }
        }
        ?>
    </tr>