<form class="container form-control" action="add_serie" method="POST">
    <div class="mb-3">
        <label for="name_proyect" class="form-label">Nombre de la Serie:</label>
        <input type="text" class="form-control" name="name_serie" placeholder="Nombre del Proyecto">
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Decripción del Proyecto:</label>
        <textarea class="form-control" name="description" rows="3"></textarea>
    </div>
    <?php
        if(!empty($error)){
            echo"<div class='alert alert-danger alert-dismissible fade show' role='alert'>
            <strong>$error</strong>
            <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
          </div>";
        }
    ?>
    <button class="btn btn-primary" type="submit">Agregar</button>
</form>